function isProcessable() {
    // Add your condition to check if the process is valid or not
    // For example,
    // if (/* your condition here */) {
    //     return true;
    // } else {
    //     return false;
    // }
    // Example condition: checking if a number is greater than 10
    if (num > 10) {
        return true;
    } else {
        return false;
    }
}

const is_processable = isProcessable();
console.log(is_processable);
