function isProcessable() {
    // Add your condition to check if the process is valid or not
    // For example,
    // if (/* your condition here */) {
    //     return true;
    // } else {
    //     return false;
    // }
    return false;
}

is_processable = isProcessable();
