name: Black
description: Extensions to the base objects from the core JavaScript library.
url: https://github.com/killdream/Black
author:
  name: Killdream
  email: killdream@example.com
  url: https://killdream.github.io/
license: MIT
version: 0.3.0
homepage: https://github.com/killdream/Black#readme
bugs: https://github.com/killdream/Black/issues
repository:
  type: git
  url: https://github.com/killdream/Black.git
  commit: master
download: https://github.com/killdream/Black/archive/master.zip
main: index.js
keywords:
  - JavaScript
  - extensions
  - objects
  - core

